import {contexts,names,calculate,atOrBefore,lineStyle,signalEnvelope} from './math.mjs';
import {screen,projectedPoints,displayCapture} from './registry.mjs';
import {computeAverages,cloudPolygons,normalizeEnvelope,specs,palette} from '../chart-workshop/model.mjs';
import {dailyCurveAnchors} from '../chart-workshop/layout.mjs';
import {cloudInk,ribbonTone,dayChange,viewMessage,sharedView} from '../chart-workshop/station-bridge.mjs';
import {traceStation,timeIndex,indexTime,clampView,wireStationGestures,viewForTimes} from '../chart-workshop/station-renderer.mjs';
const $=s=>document.querySelector(s),canvas=$('#chart'),ctx=canvas.getContext('2d'),stage=$('#stage');
const selected=new Set(contexts),cache=new Map();let fans=[],daily=[],bars=[],quote=null,view={start:0,end:100},request=0,geometry=null,envelopes=[],activeSymbol='',hoverX=null,panels=[],plotWidth=500;
const endpoint=location.hostname==='localhost'||location.hostname==='127.0.0.1'?'/workshop-data':'/api/cloud-workshop-candles';
const fmt=n=>Number.isFinite(n)?n.toLocaleString('en-US',{maximumFractionDigits:2}):'—',pct=n=>(n>=0?'+':'')+n.toFixed(2)+'%';
const familyName={rsi:'RSI',k:'Stoch %K',w:'W%R +100'};
const family={rsi:'#5576ff',k:'#ff00a8',w:'#38cbbd',signal:'#6584ff'};
const geometryMode=()=>$('#template').value==='geometry';
for(let i=0;i<contexts.length;i++){let b=document.createElement('button');b.type='button';b.textContent=names[i];b.className='on';b.onclick=()=>{selected.has(contexts[i])?selected.delete(contexts[i]):selected.add(contexts[i]);b.classList.toggle('on',selected.has(contexts[i]));draw();};$('#sources').append(b);}
async function read(tf,symbol){const key=symbol+':'+tf;if(cache.has(key))return cache.get(key);const p=(async()=>{const r=await fetch(`${endpoint}?symbol=${encodeURIComponent(symbol)}&tf=${encodeURIComponent(tf)}&limit=1200`);if(!r.ok)throw Error(tf+' unavailable ('+r.status+')');const e=normalizeEnvelope(await r.json());if(e.symbol!==symbol||e.tf!==tf)throw Error('Source identity mismatch');return e;})();cache.set(key,p);try{return await p;}catch(e){cache.delete(key);throw e;}}
let pendingViewport=null;
async function load(){if(bars.length>1&&activeSymbol===$('#symbol').value.trim().toUpperCase()&&!geometryMode())pendingViewport={from:indexTime(bars,view.start),to:indexTime(bars,view.end)};else pendingViewport=null;const id=++request;$('#status').textContent='Loading source candles…';$('#ticker').textContent='…';fans=[];bars=[];daily=[];quote=null;envelopes=[];$('#sources').hidden=geometryMode();for(const option of $('#tf').options)option.disabled=geometryMode()&&!['240','D','W'].includes(option.value);draw();
 if(geometryMode()){try{const r=await fetch('./geometry-capture.json');if(!r.ok)throw Error('Geometry capture unavailable');geometry=await r.json();if(id!==request)return;activeSymbol=geometry.symbol;geometryBars();$('#status').textContent='Frozen MCP capture · BTC 4H + daily rails persist across display timeframes';$('#coverage').textContent=geometry.captures.map(c=>`${c.sourceTF}: ${c.rails.length} resolved original rails; ${c.unresolved} unresolved primitive endpoints retained in evidence, excluded from rendering`).join('\n');$('#explanation').textContent='These are captured Trendoscope rails. Both source timeframes are drawn together. Changing Daily/Weekly display only aggregates the captured price bars. Dotted continuations preserve source-bar slope and stop at the last available source timestamp. Confirmation times and pattern names are unavailable in this snapshot, so this is visual evidence, not historical event statistics.';reset();}catch(e){$('#status').textContent=e.message;}return;}
 const symbol=$('#symbol').value.trim().toUpperCase();if(!/^[A-Z][A-Z0-9.-]{0,9}$/.test(symbol)){$('#status').textContent='Enter a stock symbol.';return;}
 activeSymbol=symbol;const failures=[];const queue=[...new Set(['D',$('#tf').value,...contexts])];let at=0;const results=new Map();
 await Promise.all(Array.from({length:3},async()=>{while(at<queue.length){const tf=queue[at++];try{const e=await read(tf,symbol);results.set(tf,e);}catch(e){failures.push(tf+': '+e.message);}}}));if(id!==request)return;
 envelopes=[...results.values()];daily=results.has('D')?computeAverages(results.get('D').series):[];bars=results.get($('#tf').value)?.series||[];
 fans=contexts.flatMap((tf,rank)=>results.has(tf)?[{tf,name:names[rank],rank,rows:calculate(results.get(tf).series)}]:[]);
 try{const r=await fetch('/api/cloud-workshop-quote?symbol='+symbol);if(r.ok){const q=await r.json();if(q.symbol===symbol&&q.quote?.symbol===symbol&&id===request)quote=q.quote;}}catch{}if(id!==request)return;
 $('#status').textContent=`${symbol} · ${fans.length}/10 source contexts · provider candles, local review calculations${failures.length?' · missing: '+failures.join('; '):''}`;
 $('#coverage').textContent=envelopes.map(e=>`${e.tf}: ${e.series.length} bars · ${new Date(e.series[0].t).toISOString().slice(0,10)} → ${new Date(e.series.at(-1).t).toISOString().slice(0,10)} · ${e.provider} · ${e.price_basis} · ${e.session_anchor||'session unspecified'}`).join('\n');
 $('#explanation').textContent='Three review templates use one shared canvas and viewport. Combined maps Williams to 0–100 (+100); RSI and stochastic already use 0–100. Shifted Williams equals raw stochastic range position; K is its SMA3. These curves are related, not independent votes. Signal band is optional and defaults off. Native source values are held until their next confirmation, never cosmetically smoothed.';reset();
}
function geometryBars(){const base=geometry.captures[0].sourceBars;if(!['240','D','W'].includes($('#tf').value))$('#tf').value='240';bars=displayCapture(base,$('#tf').value);quote=null;}
function reset(){view=pendingViewport&&bars.length>1?viewForTimes(bars,pendingViewport.from,pendingViewport.to):{start:Math.max(0,bars.length-180),end:Math.max(1,bars.length-1)};pendingViewport=null;draw();}
function draw(){document.body.dataset.template=$('#template').value;const w=stage.clientWidth,h=stage.clientHeight,dpr=devicePixelRatio||1;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);$('#labels').replaceChildren();$('#screen').replaceChildren();if(bars.length<2)return;
 view=clampView(view,bars.length);const visible=bars.slice(Math.max(0,Math.floor(view.start)),Math.ceil(view.end)+1);const span=view.end-view.start,used=fans.filter(f=>selected.has(f.tf));plotWidth=Math.max(130,w-260);const x=t=>12+(timeIndex(bars,t)-view.start)/span*plotWidth;const from=indexTime(bars,view.start),to=indexTime(bars,view.end),latest=view.end>=bars.length-1-.1;
 const template=$('#template').value;const lower=template==='combined'?['combined']:template==='geometry'?[]:template==='full'?['rsi','w','k','macd','volume']:['rsi','w','k'];const ph=lower.length?Math.max(220,h*(template==='combined'?.62:.42)):h-26;panels=[{kind:'price',top:0,height:ph},...lower.map((kind,i)=>({kind,top:ph+i*(h-ph-22)/lower.length,height:(h-ph-22)/lower.length}))];
 const dc=dayChange(quote);$('#ticker').textContent=activeSymbol;$('#change').textContent=geometryMode()?'captured study':dc.text;$('#change').style.color=dc.color;
 const values=visible.flatMap(b=>$('#style').value==='candles'?[b.l,b.h]:[b.c]),min=Math.min(...values),max=Math.max(...values),range=max-min||1;const y=p=>15+(max+range*.05-p)/(range*1.1)*(ph-38);
 const segment=(points,color,width=1,dash=[])=>{ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.beginPath();let started=false;for(const p of points){if(!Number.isFinite(p.p)){started=false;continue;}if(!started){ctx.moveTo(x(p.t),p.p);started=true;}else ctx.lineTo(x(p.t),p.p);}ctx.stroke();ctx.setLineDash([]);};
 const label=(text,yy,color,size=11,col=0)=>{if(yy<5||yy>h-20||!latest)return;const el=document.createElement('div');el.className='label';el.textContent=text;el.style.cssText=`left:${plotWidth+20+col*112}px;top:${yy}px;color:${color};font-size:${size}px`;$('#labels').append(el);};
 ctx.save();ctx.beginPath();ctx.rect(8,0,plotWidth+6,ph-8);ctx.clip();
 if(!geometryMode()&&daily.length){const rows=dailyCurveAnchors(daily,to).filter((r,i,a)=>r.time>=from||a[i+1]?.time>=from);for(let i=1;i<rows.length;i++)for(const p of cloudPolygons(rows[i-1],rows[i])){const xa=x(rows[i-1].time)+(x(rows[i].time)-x(rows[i-1].time))*p.t0,xb=x(rows[i-1].time)+(x(rows[i].time)-x(rows[i-1].time))*p.t1;ctx.fillStyle=cloudInk(p);ctx.beginPath();ctx.moveTo(xa,y(p.previousLo));ctx.lineTo(xb,y(p.lo));ctx.lineTo(xb,y(p.hi));ctx.lineTo(xa,y(p.previousHi));ctx.fill();}for(const s of specs.filter(s=>s.key!=='s100'||$('#level100').checked)){for(let i=1;i<rows.length;i++){const a=rows[i-1],b=rows[i];if(!Number.isFinite(a[s.key])||!Number.isFinite(b[s.key]))continue;const bull=s.stateKey==='price'?visible.at(-1).c>=b[s.key]:b[s.stateKey];segment([{t:a.time,p:y(a[s.key])},{t:b.time,p:y(b[s.key])}],ribbonTone(bull?palette.blue:palette.pink,bull?s.blueOpacity:s.pinkOpacity),Math.min(3,s.width*.65),s.style==='dashed'?[3,5]:[]);}const last=rows.at(-1);if(last&&Number.isFinite(last[s.key])&&y(last[s.key])>10&&y(last[s.key])<ph-15)label(s.label+' '+fmt(last[s.key]),y(last[s.key]),visible.at(-1).c>=last[s.key]?'#5576ff':'#e33fa3',10+s.width*.3);}}
 if(geometryMode()){for(const capture of geometry.captures){for(const rail of capture.rails){const pts=projectedPoints(rail,capture.sourceBars).filter(p=>p.t>=from&&p.t<=to),duration=rail.i2-rail.i1;const alpha=.4+Math.min(.5,Math.abs(duration)/200),color=rail.role==='upper'?`rgba(0,255,163,${alpha})`:`rgba(255,45,85,${alpha})`;segment(pts.filter(p=>!p.continuation).map(p=>({t:p.t,p:y(p.p)})),color,capture.sourceTF==='D'?2.5:1.2);if($('#tail').checked){const tail=pts.filter(p=>p.continuation);if(tail.length)segment([{t:rail.t2,p:y(rail.p2)},...tail.map(p=>({t:p.t,p:y(p.p)}))],color,.75+Math.min(.7,Math.abs(duration)/200),[2,5]);}}}}
 ctx.strokeStyle=dc.color;ctx.lineWidth=4;ctx.lineJoin='round';ctx.lineCap='round';if($('#style').value==='line'){ctx.beginPath();traceStation(ctx,visible.map(b=>({x:x(b.t),y:y(b.c)})));ctx.stroke();}else for(const b of visible){ctx.strokeStyle=b.c>=b.o?'#00ffa3':'#ff2d55';ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x(b.t),y(b.h));ctx.lineTo(x(b.t),y(b.l));ctx.stroke();ctx.fillRect(x(b.t)-Math.min(5,plotWidth/span*.3),Math.min(y(b.o),y(b.c)),Math.max(1,Math.min(10,plotWidth/span*.6)),Math.max(1,Math.abs(y(b.o)-y(b.c))));}ctx.restore();
 const seriesPoints=(rows,key,yy)=>{const left=atOrBefore(rows,from);return [...(left?[{t:from,p:yy(left[key])}]:[]),...rows.filter(r=>r.t>=from&&r.t<=to).flatMap((r,i,a)=>{const prior=i?a[i-1]:left;return [...(prior?[{t:r.t,p:yy(prior[key])}]:[]),{t:r.t,p:yy(r[key])}];}),...(atOrBefore(rows,to)?[{t:to,p:yy(atOrBefore(rows,to)[key])}]:[])];};
 for(const pane of panels.slice(1)){const top=pane.top+20,bottom=pane.top+pane.height-10,yy=v=>Number.isFinite(v)?bottom-v/100*(bottom-top):NaN;ctx.strokeStyle='#192436';ctx.lineWidth=.7;ctx.beginPath();ctx.moveTo(0,pane.top);ctx.lineTo(w,pane.top);ctx.stroke();ctx.fillStyle='#788aa5';ctx.font='11px -apple-system,sans-serif';ctx.fillText(pane.kind==='combined'?'RSI + RANGE-POSITION OVERLAY · 0–100':pane.kind==='macd'?'MACD · DAILY 12/26/9':(pane.kind==='w'?'WILLIAMS %R +100':pane.kind==='k'?'STOCHASTIC %K':pane.kind.toUpperCase()),14,pane.top+13);ctx.save();ctx.beginPath();ctx.rect(8,top,plotWidth+6,bottom-top);ctx.clip();
 if(['combined','rsi','w','k'].includes(pane.kind)){if($('#zones').checked){const levels=pane.kind==='rsi'||pane.kind==='combined'?[30,50,70]:[20,50,80];for(const z of levels){ctx.fillStyle=z===50?'#3455ff15':'#5576ff1d';ctx.fillRect(10,yy(z+2),plotWidth,yy(z-2)-yy(z+2));}}
 if($('#signal').checked&&['combined','rsi'].includes(pane.kind)){let band=visible.map(b=>({t:b.t,...signalEnvelope(used,b.t)})).filter(b=>Number.isFinite(b.lo));if(band.length){ctx.fillStyle='#7896ff35';ctx.beginPath();band.forEach((b,i)=>i?ctx.lineTo(x(b.t),yy(b.lo)):ctx.moveTo(x(b.t),yy(b.lo)));band.slice().reverse().forEach(b=>ctx.lineTo(x(b.t),yy(b.hi)));ctx.fill();}}
 const keys=pane.kind==='combined'?['rsi','k','w'].filter(k=>$(k==='k'?'#stoch':k==='w'?'#williams':'#rsi').checked):[pane.kind];const placed=[];for(const f of used.slice().reverse())for(const key of keys){const style=lineStyle(f.rank,span),color=family[key];ctx.globalAlpha=style.alpha;segment(seriesPoints(f.rows,key,yy),color,style.width,key==='k'?[5,3]:key==='w'?[1,4]:[]);ctx.globalAlpha=1;const v=atOrBefore(f.rows,to)?.[key];if(Number.isFinite(v)){const py=yy(v),neighbors=placed.filter(p=>Math.abs(p-py)<13).length;placed.push(py);if(neighbors<2)label(`${f.name} ${familyName[key]}`,py,color,style.font,neighbors);}}
 }else if(pane.kind==='macd'){const f=fans.find(f=>f.tf==='D'),rows=f?.rows.filter(r=>r.t>=from&&r.t<=to)||[],extent=Math.max(.001,...rows.flatMap(r=>[r.macd,r.macdSignal,r.hist].filter(Number.isFinite).map(Math.abs))),my=v=>Number.isFinite(v)?(top+bottom)/2-v/extent*(bottom-top)*.44:NaN;ctx.fillStyle='#3455ff';for(const r of rows){if(!Number.isFinite(r.hist))continue;ctx.fillStyle=r.hist>=0?'#00ffa366':'#ff2d5566';ctx.fillRect(x(r.t),Math.min(my(0),my(r.hist)),2,Math.abs(my(r.hist)-my(0)));}if(f){segment(seriesPoints(f.rows,'macd',my),'#5576ff',1.5);segment(seriesPoints(f.rows,'macdSignal',my),'#ff00a8',1,[3,3]);}}else{const maxv=Math.max(1,...visible.map(b=>b.v));for(const b of visible){ctx.fillStyle=b.c>=b.o?'#00ffa34d':'#ff2d554d';const bh=b.v/maxv*(bottom-top);ctx.fillRect(x(b.t),bottom-bh,Math.max(1,plotWidth/span*.6),bh);}const volumeRows=calculate(bars);const rv=atOrBefore(volumeRows,to)?.rvol;label('RVOL20 '+fmt(rv),top+12,'#91a3bf');}ctx.restore();}
 ctx.font='10px -apple-system,sans-serif';ctx.fillStyle='#667d99';for(let i=0;i<5;i++){const t=indexTime(bars,view.start+span*i/4);ctx.fillText(new Date(t).toLocaleDateString('en-US',{month:'short',day:'numeric',year:'2-digit'}),12+plotWidth*i/4,h-5);}
 if(hoverX!==null){ctx.strokeStyle='#546b8066';ctx.beginPath();ctx.moveTo(hoverX,0);ctx.lineTo(hoverX,h-20);ctx.stroke();}
 if(!geometryMode()){const table=document.createElement('table');table.innerHTML='<tr><th>Source</th><th>RSI14</th><th>RSI SMA14</th><th>Williams +100</th><th>Stochastic %K</th><th>Stochastic %D</th></tr>';for(const f of used){const r=atOrBefore(f.rows,to);const tr=document.createElement('tr');for(const value of [f.name,...['rsi','signal','w','k','d'].map(k=>fmt(r?.[k]))]){const td=document.createElement('td');td.textContent=value;tr.append(td);}table.append(tr);}$('#screen').append(table);}
 if(geometryMode()){const nearest=screen(geometry,to,visible.at(-1).c).slice(0,8);const table=document.createElement('table');table.innerHTML='<tr><th>Source</th><th>Boundary</th><th>Level</th><th>Price distance</th><th>Segment</th></tr>';for(const r of nearest){const tr=document.createElement('tr');for(const value of [r.sourceTF,r.role,fmt(r.value),pct(r.distancePct),r.continuation?'Continuation':'Original']){const td=document.createElement('td');td.textContent=value;tr.append(td);}table.append(tr);}$('#screen').append(table);}
}
function exportData(){const body={version:1,at:new Date().toISOString(),template:$('#template').value,symbol:activeSymbol,displayTF:$('#tf').value,sourceTFs:[...selected],confirmationPolicy:'previous-source-value-at-next-source-open',envelopes:geometryMode()?undefined:envelopes,geometry:geometryMode()?geometry:undefined};const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(body)],{type:'application/json'}));a.href=url;a.download='scintilla-indicator-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
wireStationGestures(canvas,{getView:()=>view,getCount:()=>bars.length,getWidth:()=>plotWidth,setView:v=>{view=v;draw();if(bars.length&&window.parent!==window)window.parent.postMessage(viewMessage(activeSymbol,indexTime(bars,view.start),indexTime(bars,view.end),view.end>=bars.length-1),location.origin);},hover:(x)=>{hoverX=x;if(bars.length){const b=bars[Math.max(0,Math.min(bars.length-1,Math.round(view.start+(x-12)/plotWidth*(view.end-view.start))))];$('#readout').textContent=new Date(b.t).toLocaleString()+' · '+fmt(b.c);}draw();},clearHover:()=>{hoverX=null;$('#readout').textContent='';draw();},reset});
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==window.parent)return;const v=sharedView(e.data);if(v&&bars.length){view=viewForTimes(bars,v.from,v.to);draw();}});
$('#controls').onsubmit=e=>{e.preventDefault();load();};$('#template').onchange=()=>load();$('#tf').onchange=async()=>{if(geometryMode()){geometryBars();reset();}else load();};$('#style').onchange=draw;$('#reset').onclick=reset;$('#export').onclick=exportData;for(const el of $('#options').querySelectorAll('input'))el.onchange=draw;
new ResizeObserver(draw).observe(stage);const params=new URLSearchParams(location.search);if(['combined','separate','full','geometry'].includes(params.get('view')))$('#template').value=params.get('view');if(params.get('symbol'))$('#symbol').value=params.get('symbol');load();
